import type { ExperienceFilterItem, ExperienceItem, ExperienceStat } from "./experience-details.types";

export const CONTACT_EMAIL = "fadhluibnua@gmail.com";

export const experienceStats: ExperienceStat[] = [
  { value: "7", label: "Total Experiences" },
  { value: "3", label: "Ongoing Roles" },
  { value: "5+", label: "Technical Contributions" },
];

export const experienceFilters: ExperienceFilterItem[] = [
  { value: "all", label: "All" },
  { value: "professional", label: "Professional" },
  { value: "internship", label: "Internship" },
  { value: "organization", label: "Organization" },
  { value: "ongoing", label: "Ongoing" },
];

export const experienceItems: ExperienceItem[] = [
  {
    id: "rapier-technology-international",
    company: "PT. Rapier Technology International",
    meta: "Backend Developer · Onsite — Semarang · January 2026 — Present",
    logo: "RTI",
    logoImage: "/assets/experience/rapier.jpg",
    type: "Internship",
    role: "Backend Developer",
    duration: "January 2026 — Present",
    status: "ongoing",
    categories: ["internship", "ongoing"],
    summary: "Membuat API untuk sistem POS dan VMS. Melakukan analisis kebutuhan sebelum membangun sebuah API.",
    contributions: [
      "Menganalisis kebutuhan sistem dan fitur sebelum pengembangan API.",
      "Membangun arsitektur backend untuk mendukung sistem Point of Sale (POS) dan Vendor Management System (VMS).",
      "Mengelola database menggunakan PostgreSQL, MySQL, dan Redis untuk performa optimal.",
    ],
    stacks: ["JavaScript", "TypeScript", "Node.js", "Express", "PostgreSQL", "MySQL", "Sequelize", "Redis", "S3 Storage", "Hoppscotch"],
  },
  {
    id: "universitas-negeri-semarang-1",
    company: "Universitas Negeri Semarang",
    meta: "Member of Lecturer Research · Hybrid — Semarang · January 2025 — Present",
    logo: "UN",
    logoImage: "/assets/experience/unnes.jpg",
    type: "Work Partime",
    role: "Backend Developer (Research)",
    duration: "January 2025 — Present",
    status: "ongoing",
    categories: ["professional", "ongoing"],
    summary: "Collaborated in a research and development team to design and build a web-based application from scratch for managing students’ memorization progress in a multi-branch Islamic boarding school.",
    contributions: [
      "Analyzed user needs and operational workflows across different branches to define system requirements and core features.",
      "Designed backend logic and database structure to track memorization progress, attendance, and student data.",
      "Developed web application features using Laravel for backend services and React.js for frontend interfaces.",
      "Integrated role-based access to support administrators, teachers, and supervisors.",
      "Ensured data consistency and scalability to support multiple branches within a single system.",
    ],
    stacks: ["PHP", "Laravel", "React", "MySQL"],
  },
  {
    id: "universitas-negeri-semarang-2",
    company: "Universitas Negeri Semarang",
    meta: "Member of Lecturer Research · Hybrid — Semarang · January 2025 — Present",
    logo: "UN",
    logoImage: "/assets/experience/unnes.jpg",
    type: "Work Partime",
    role: "System Analyst & Prototyper (Research)",
    duration: "January 2025 — Present",
    status: "ongoing",
    categories: ["professional", "ongoing"],
    summary: "Collaborated with a research team to design a prototype system for detecting and classifying students’ potential in the field of athletics.",
    contributions: [
      "Conducted early-stage analysis to define key indicators, system flow, and user interactions required for talent identification.",
      "Translated research objectives into functional system requirements and interaction flows.",
      "Designed end-to-end UI/UX prototypes to visualize the complete system workflow, from data input to classification output.",
      "Created UML diagrams and system flow models to support research documentation and future system implementation.",
      "Delivered a high-fidelity prototype using Figma as a foundation for further development and evaluation.",
    ],
    stacks: ["PHP", "Laravel", "React", "MySQL", "Figma", "UML"],
  },
  {
    id: "sinar-research",
    company: "PT. Sinar Edukasi Riset (Sinar Research)",
    meta: "AI Developer and Website Manager · Remote · August 2025 — Present",
    logo: "SR",
    logoImage: "/assets/experience/sinar.jpg",
    type: "Work Fulltime",
    role: "FullStack & RAG Developer",
    duration: "August 2025 — Present",
    status: "ongoing",
    categories: ["professional", "ongoing"],
    summary: "Developed AI-powered features to assist academic research processes, including workflow design, prompt engineering, and system logic formulation.",
    contributions: [
      "Implemented testing pipelines to ensure AI output accuracy, consistency, and usability.",
      "Managed website infrastructure, resolved technical issues, and ensured content accuracy and performance.",
      "Applied SEO best practices to improve organic visibility and search ranking.",
      "Collaborated cross-functionally with Digital Marketing and Research teams.",
    ],
    stacks: ["AI Development", "RAG", "Prompt Engineering", "SEO", "Website Management"],
  },
  {
    id: "wiyora-technology",
    company: "PT. Wiyora Technology",
    meta: "Backend Developer · Hybrid — Semarang · August 2025 — January 2026",
    logo: "WT",
    logoImage: "/assets/experience/wiyora.jpg",
    type: "Internship",
    role: "Backend Developer",
    duration: "August 2025 — January 2026",
    status: "completed",
    categories: ["internship"],
    summary: "Built backend architecture for a facial recognition–based attendance system using TypeScript.",
    contributions: [
      "Designed REST APIs and database schemas to support real-time attendance and identity verification.",
      "Integrated AI facial recognition pipelines with backend services.",
      "Applied containerization using Docker for consistent development and deployment environments.",
      "Worked in a Linux-based production environment and collaborated cross-functionally with frontend and AI teams.",
    ],
    stacks: ["TypeScript", "Bun", "Hono", "MySQL", "Docker", "Linux"],
  },
  {
    id: "kementrian-esdm",
    company: "Kementrian ESDM",
    meta: "Management and IT Specialist · Onsite — Semarang · July 2025 — August 2025",
    logo: "ES",
    logoImage: "/assets/experience/esdm.jpg",
    type: "Internship",
    role: "FullStack Developer",
    duration: "July 2025 — August 2025",
    status: "completed",
    categories: ["internship"],
    summary: "Designed and implemented a web-based asset and document management system for a government institution.",
    contributions: [
      "Translated administrative workflows into structured system features and database models.",
      "Built backend services using Laravel and MySQL to manage asset lifecycle and document records.",
      "Applied access control to support different administrative roles.",
    ],
    stacks: ["PHP", "Laravel", "MySQL", "System Design"],
  },
  {
    id: "telkom-test-house",
    company: "Telkom Test House",
    meta: "Web Developer Internship · Onsite — Bandung · April 2022 — September 2022",
    logo: "TTH",
    logoImage: "/assets/experience/tth.jpg",
    type: "Internship",
    role: "Web Developer",
    duration: "April 2022 — September 2022",
    status: "completed",
    categories: ["internship"],
    summary: "Designing Unified Modeling Language (UML) for the company's internal system and developing web solutions.",
    contributions: [
      "Designed website interfaces and application workflows.",
      "Developed web features using Laravel and Livewire.",
      "Set up and configured servers for website hosting.",
    ],
    stacks: ["PHP", "Laravel", "Livewire", "MySQL", "UML", "Server Administration"],
  },
  {
    id: "i-secret",
    company: "I-Secret",
    meta: "Programming Division · Campus Organizations · February 2025 — December 2025",
    logo: "IS",
    logoImage: "/assets/experience/i-secret.jpg",
    type: "Members of the Organization",
    role: "Lead Backend Developer",
    duration: "February 2025 — December 2025",
    status: "completed",
    categories: ["organization"],
    summary: "Membangun website portofolio organisasi I-Secret sebagai Lead dari tim Backend.",
    contributions: [
      "Memimpin pengembangan arsitektur backend untuk website organisasi.",
      "Mengelola basis data menggunakan MySQL dan logika aplikasi dengan Laravel.",
      "Berkolaborasi dengan tim frontend dan desain untuk memastikan integrasi fitur berjalan lancar.",
    ],
    stacks: ["PHP", "Laravel", "MySQL", "Leadership", "Teamwork"],
  },
];
